// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPCaSVJXUK00roSV84RHLGs4grndldh2M',
    appId: '1:14662269648:web:84cccd8ac81d70a85dfcd5',
    messagingSenderId: '14662269648',
    projectId: 'farmhub-1cc56',
    authDomain: 'farmhub-1cc56.firebaseapp.com',
    storageBucket: 'farmhub-1cc56.firebasestorage.app',
    measurementId: 'G-P99H7L21LT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt89_GG1cFO7SsN4vJOX8aW-dL8sTF6Jo',
    appId: '1:14662269648:android:40ad882f538d7b0d5dfcd5',
    messagingSenderId: '14662269648',
    projectId: 'farmhub-1cc56',
    storageBucket: 'farmhub-1cc56.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJJezbqv-8uVUI6610_Hl4NK9NsgJYD60',
    appId: '1:14662269648:ios:1bbcb3f46f4d69155dfcd5',
    messagingSenderId: '14662269648',
    projectId: 'farmhub-1cc56',
    storageBucket: 'farmhub-1cc56.firebasestorage.app',
    iosBundleId: 'com.example.farmHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJJezbqv-8uVUI6610_Hl4NK9NsgJYD60',
    appId: '1:14662269648:ios:1bbcb3f46f4d69155dfcd5',
    messagingSenderId: '14662269648',
    projectId: 'farmhub-1cc56',
    storageBucket: 'farmhub-1cc56.firebasestorage.app',
    iosBundleId: 'com.example.farmHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPCaSVJXUK00roSV84RHLGs4grndldh2M',
    appId: '1:14662269648:web:a4fd3bfb21e357f35dfcd5',
    messagingSenderId: '14662269648',
    projectId: 'farmhub-1cc56',
    authDomain: 'farmhub-1cc56.firebaseapp.com',
    storageBucket: 'farmhub-1cc56.firebasestorage.app',
    measurementId: 'G-LM0MFR9L2R',
  );
}
